description "build sitemaps for almost every link on artemis"

instance $x

stop on artemis-stop or runlevel [016]

respawn

nice 10
script
    . /etc/default/artemis
    wrap-job paster run --proctitle sitemaps_q$x $ARTEMIS_INI $ARTEMIS_ROOT/r2/lib/sitemaps/watcher.py -c 'watcher()'
end script
