description "update links by branch precomputed queries"

instance $x

stop on artemis-stop or runlevel [016]

respawn
respawn limit 10 5

nice 10
script
    . /etc/default/artemis
    wrap-job paster run --proctitle branch_query_q$x $ARTEMIS_INI $ARTEMIS_ROOT/r2/lib/voting.py -c "consume_branch_query_queue()"
end script
