description "the artemis app running under paster"

stop on artemis-stop or artemis-restart all or artemis-restart apps
start on artemis-start or artemis-restart all or artemis-restart apps

respawn
respawn limit 10 5

script
    . /etc/default/artemis
    wrap-job paster serve --reload $ARTEMIS_INI
end script
